UniPromecys/Controllers/AsignaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniPromecys.Models.Asignatura;
using static UniPromecys.Models.AccionesControlador;
using static UniPromecys.Models.Enum;

namespace UniPromecys.Controllers
{
    public class AsignaturaController : BaseController
    {
        private List<AsignaturaItemModel> Listado()
        {
            var listado = new List<AsignaturaItemModel> {
                new AsignaturaItemModel{
                    Id = 1,
                    Nombre = "Asignatura 1",
                    CodigoInterno = "ASIG-001",
                    Descripcion = "Descripcion de Asignatura" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                 Id = 2,
                    Nombre = "Asignatura 2",
                    CodigoInterno = "ASIG-002",
                    Descripcion = "Descripcion de Asignatura 2" ,
                    FechaCreacion = DateTime.Today},
                new AsignaturaItemModel {
                 Id = 3,
                    Nombre = "Asignatura 3",
                    CodigoInterno = "ASIG-003",
                    Descripcion = "Descripcion de Asignatura 3" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                    Id = 1,
                    Nombre = "Asignatura 1",
                    CodigoInterno = "ASIG-001",
                    Descripcion = "Descripcion de Asignatura" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                 Id = 4,
                    Nombre = "Asignatura 2",
                    CodigoInterno = "ASIG-002",
                    Descripcion = "Descripcion de Asignatura 2" ,
                    FechaCreacion = DateTime.Today},
                new AsignaturaItemModel {
                 Id = 5,
                    Nombre = "Asignatura 3",
                    CodigoInterno = "ASIG-003",
                    Descripcion = "Descripcion de Asignatura 3" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                    Id = 6,
                    Nombre = "Asignatura 1",
                    CodigoInterno = "ASIG-001",
                    Descripcion = "Descripcion de Asignatura" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                 Id = 7,
                    Nombre = "Asignatura 2",
                    CodigoInterno = "ASIG-002",
                    Descripcion = "Descripcion de Asignatura 2" ,
                    FechaCreacion = DateTime.Today},
                new AsignaturaItemModel {
                 Id = 8,
                    Nombre = "Asignatura 3",
                    CodigoInterno = "ASIG-003",
                    Descripcion = "Descripcion de Asignatura 3" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                    Id = 9,
                    Nombre = "Asignatura 1",
                    CodigoInterno = "ASIG-001",
                    Descripcion = "Descripcion de Asignatura" ,
                    FechaCreacion = DateTime.Today
                },
                new AsignaturaItemModel{
                 Id = 10,
                    Nombre = "Asignatura 2",
                    CodigoInterno = "ASIG-002",
                    Descripcion = "Descripcion de Asignatura 2" ,
                    FechaCreacion = DateTime.Today},
                new AsignaturaItemModel {
                 Id = 11,
                    Nombre = "Asignatura 3",
                    CodigoInterno = "ASIG-003",
                    Descripcion = "Descripcion de Asignatura 3" ,
                    FechaCreacion = DateTime.Today
                }
            };

            return listado;
        }
        public IActionResult Administrar()
        {
          

            var modelo = new AsignaturaAdminModel
            {
                ListadoAsignaturas = Listado()
            };

            return View("Administrar", modelo);
        }

        public IActionResult RegistrarAsignatura()
        {
            var modelo = new AsignaturaItemModel();
            modelo.Accion = Acciones.Nuevo.ToString();
            return View("RegistrarAsignatura",modelo);
        }

        [HttpPost]
        public IActionResult GuardarAsignatura(AsignaturaItemModel asignaturaItemModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("RegistrarAsignatura");
                }

                Alert("Asignatura guardada con éxito", NotificationType.success);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.ToString());
                return View();
            }

            return RedirectToAction("Administrar");
        }

        public IActionResult Editar(Int32 IdAsignatura)
        {
            var modelo = new AsignaturaItemModel();
            var Encontrado = Listado().FirstOrDefault(x => x.Id == IdAsignatura);
            modelo = Encontrado;
            modelo.Accion = Acciones.Editar.ToString();
            return View("RegistrarAsignatura", modelo);
        }

        [HttpGet]
        public IActionResult Eliminar(Int32 IdAsignatura)
        {
            Alert("Asignatura Eliminada con éxito", NotificationType.success);
            //return RedirectToAction("Administrar");
            var modelo = new AsignaturaAdminModel
            {
                ListadoAsignaturas = Listado()
            };

            return View("Administrar", modelo);
        }
    }
}

UniPromecys/Controllers/EstudianteController.cs
using Microsoft.AspNetCore.Mvc;
using UniPromecys.Models.Asignatura;
using UniPromecys.Models.Estudiante;
using static UniPromecys.Models.AccionesControlador;
using static UniPromecys.Models.Enum;

namespace UniPromecys.Controllers
{
    public class EstudianteController : BaseController
    {
        private List<EstudianteItemModel> Listado()
        {
            var listado = new List<EstudianteItemModel> {
                new EstudianteItemModel{
                    Id = 1,
                    PrimerNombre = "Isela",
                    SegundoNombre = "del Rosario",
                    PrimerApellido = "Ramos" ,
                    SegundoApellido = "Mercado",
                    NombreCompleto = "Isela del Rosario Ramos Mercado",
                    Carnet = "2016-100P",
                    IdSolvencia = 1,
                    Solvencia = "20% Descuento"
                }
            };

            return listado;
        }

        public IActionResult Administrar()
        {


            var modelo = new EstudianteAdminModel
            {
                ListadoEstudiantes = Listado()
            };

            return View("Administrar", modelo);
        }

        public IActionResult RegistrarEstudiante()
        {
            var modelo = new EstudianteItemModel();
            modelo.Accion = Acciones.Nuevo.ToString();
            return View("RegistrarEstudiante", modelo);
        }

        [HttpPost]
        public IActionResult GuardarEstudiante(EstudianteItemModel estudianteItemModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("RegistrarEstudiante");
                }

                Alert("Estudiante guardado con éxito", NotificationType.success);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                return View();
            }

            return RedirectToAction("Administrar",estudianteItemModel);
        }

        public IActionResult Editar(Int32 IdEstudiante)
        {
            var modelo = new EstudianteItemModel();
            var Encontrado = Listado().FirstOrDefault(x => x.Id == IdEstudiante);
            modelo = Encontrado;
            modelo.Accion = Acciones.Editar.ToString();
            return View("RegistrarEstudiante", modelo);
        }

        [HttpGet]
        public IActionResult Eliminar(Int32 IdEstudiante)
        {
            Alert("Estudiante Eliminado con éxito", NotificationType.success);
            //return RedirectToAction("Administrar");
            var modelo = new EstudianteAdminModel
            {
                ListadoEstudiantes = Listado()
            };

            return View("Administrar", modelo);
        }
    }
}

UniPromecys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" />
    <title>@ViewData["Title"] - Promecys_V1</title>

    @*<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
    asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
    asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>*@
    <!-- Bootstrap CSS CDN -->
    <link href="~/css/sweetalert2.css" rel="stylesheet" />
    <script src="~/js/sweetalert2.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/Assets/MasterPage/css/MasterPage.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />


    <!-- Font Awesome JS -->
    @*<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>*@
    <script src="https://use.fontawesome.com/9514f4542e.js"></script>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Promecys_V1</a>
    </div>
    <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
    </ul>
    </div>
    </div>
    </nav>*@
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                @*<h3>Bootstrap Sidebar</h3>*@
                <img src="../Assets/images/Promecys (1).png">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fa fa-eye-slash"></i>
                    @*<span>Ocultar</span>*@
                </button>
            </div>


            <ul class="list-unstyled components">
                <li id="sidebarCollapse_" class="btn btn-info">
                    <i class="fa fa-eye"></i>
                    @*<span>Ocultar</span>*@
                </li>
                <li id="liseleccionado_Asignatura" class="">
                    <a href="#AsignaturaSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fa fa-book"></i>
                        Asignaturas
                    </a>
                    <ul class="collapse list-unstyled" id="AsignaturaSubmenu">
                        <li>
                            <a asp-area="" asp-controller="Asignatura" asp-action="Administrar">Listar Asignaturas</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Asignatura" asp-action="RegistrarAsignatura">Nueva Asignatura</a>
                        </li>
                    </ul>
                </li>
                <li id="liSeleccionado_Estudiante" class="">
                    <a href="#EsutidanteSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fa fa-graduation-cap"></i>
                        Estudiantes
                    </a>
                    <ul class="collapse list-unstyled" id="EsutidanteSubmenu">
                        <li>
                            <a asp-area="" asp-controller="Estudiante" asp-action="Administrar">Listar Estudiantes</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Estudiante" asp-action="RegistrarEstudiante">Nuevo Estudiante</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse_1" class="btn btn-info">
                    <i class="fa fa-eye-slash"></i>
                    @*<span>Ocultar</span>*@
                </button>

                <span style="color:rgba(0,52,133,255); font-weight:bold; font-size:20px;">UNIVERSIDAD NACIONAL DE INGENIERIA - PROMECYS</span>

                <a type="button" id="" class="btn btn-info" href="/InicioSesion/InicioSesion">
                    <i class="fa fa-sign-out"></i>
                    @*<span>Cerrar Sesion</span>*@
                </a>

                @*<button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="#">Page</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Page</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Page</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Page</a>
                </li>
                </ul>
                </div>*@
            </div>
        </nav>
        @Html.Partial("_NotificationPanel")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Date.ToString("D") - Dev By Isela Ramos, Kelin Martinez, Pedro Chávez</p>
        </footer>
    </div>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <script src="~/Assets/MasterPage/js/MasterPage.js"></script>
    @*<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
    asp-fallback-test="window.jQuery"
    crossorigin="anonymous"
    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
    crossorigin="anonymous"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>

UniPromecys/Views/Shared/_NotificationPanel.cshtml
@if (TempData["notification"] != null)
{
    @Html.Raw(TempData["notification"])}